#!/bin/bash

#find ../../examples/ -type f -name *.xml -exec sed -i '' '/^<!DOCTYPE/d' {} +
find ../../examples/ -type f -name *.xml -exec sed -i '' 's/^<!DOCTYPE.*$/<!--&-->/g' {} +
./fingerprints "$@"
find ../../examples/ -type f -name *.xml -exec sed -i '' 's/^<!--<!DOCTYPE.*-->$/&/g' {} +
